language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: aRUX1K0096B1gQyQ/yUbOcubwGXt/5Me0XGL0jAQugHFRBU8OM1XemQrbHLSUFJo40zf7sHBKAhz8hOlRgDdA6xqr37ssUkYjqms/fHhi6BiLqBi7b7kphjPAJ2wI+TEITvRMi5BKb/Cktj48TaMA0OUTmNKd3YwvHEo158PAoA7qakUJzw8+OrOQPZ88yZ9433sPOWAzFkfRwLLdKAd555tZl3oCuWGZbb+cCS+aHPAcxti2c0MIP0JKpszv2kPxZE3l4N+ECWoeyxscuP/j/YG3vEw0PZlCQLGStffReToslzQcfa3HkrnZklveU+dKSsgl0qnQ9B5HXIUPsu3393FZSxvR76Ivu95U+9Ecxc7yDpokJOJ57AoJbh98zcc5bPdtjWXgqsI+fFkNcS0TLfTxCzplyRdWbFkUUGpt+R+mPeUugLKIU6BhiBTfmw/ZGchM8m07dj6OsRPLMA68mvfxTIVM0ZhoIII0mb8A+4Qp0fsOh+vrgFCZvmMq8cOIOKdwcaJSJkoOClTOSDfTYYfkXO2qoFH1Qga3ohBBIzJTqH/g+6qmdeFgHwq+TMqQFMqYTpHDL+tWnNAOIzel6VDwz8QItl9yntWodlcwBnBitRxyE2m3uTvAJ10jyxt47KLTAj9gNv8E+OSDjMzdqxYp9PtrFDf4U5mnMe0zxk=
    on:
      tags: true
      repo: higlass/higlass-labelled-points-track
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: hCKQH/ickwzXBpnl/jyVd/8yc14N8rsmdMMlHOHH4Nspt2PhqhxYSVvMt9rLF4anHmp5HfgxWYxPsigDdhZqfY6j/k1LixpVP5LNp5nd3ESv88kW0m4uwVTU7Z8Ig3ucS65cFcONoDYPERGCPZVuJYGGwDiF6BnYOcWN/ah7WD6W7o/52TjevEemI6PfhzroEOUVYHOhxvfSShpWdzl4RkFVnV5SoAOPVaIRTCaXMcuivTYRv3/301lH7dtjRhGlo3lVhKX4M+vZBqQB0Nc8+mp239lLo03ybVUjDf5RCiNaEuOFuIWOjFQ9K+4w/62wy8eH+CRrCzlPHBw3WA5mtztB0uVBTD5yD8QWgrf9jdesREtpFk6dgldhbU4csCikN7qPTmwxW1q3F2/h3xUZd4O+ybmyXFek0iXTAWM3ACAfweTwyG/JFal/n0DduorzGcE2zEMwLzvyuG3H+F7+IwYppjfKFM4fKpbrr4SA7EyDtMn5EiFK46cqhH/Q0nA7bZPbtQ6jEx9ypjjYIhtqjwg8vqsBWe71c0I3hUL8Cd1pijXipW8HigVM29KzdYGXPBVt0dRP/rcsCx8Qm2yWczscuX7ekHa4GoLCt2cGBJv6OI0vv4nTrBxmYWydMrDUjte0whs3o6gCd5GK9rN+bwhqgx5W8Kd4ffCIkkJ3dwo=
    file: dist.zip
    on:
      repo: higlass/higlass-labelled-points-track
