language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: 05dpPKrCrrNqIvzlLiABe2BLcs8RhtDamaeKD22OZl9we2zUH0DKunIZmKz8Qz+Xzn3xGufoKzhqCXK6abrwH5C1rVv2U8m2XdV6n47pJWKba4oVR1DxcvOGQSgQf7CgzDE4TQgDlrXSBG26xCOSurTEX6FC8zfbzfF/UgxGIcz2K8Y8ggoexl+5RHqFpj7H9l5K9F4+APubqRI+9Fjq/1vQmdoRwbtL5iwFtCecJDkN4EyHD7JFcAj3fZ5yBquysZ5XB48SpQBqiea/3TfblKa1xviCjTS7XTJqJK3T0JEmn4tMzBq8LoGXtEiUm9jRsA4yVyoIdOp8LlpIpFcsEUjyVEsRrL6Nvv0O5efsltqDrQIuYP76NCT5Oqncsgn27KBcHeUFlT0ePuq+Q3bJNSTExwtahPUCxhD34nul9z5SQhzUEzVG5AGewM6Ar/Lw2Yav19X+S9iBSHmvMyc/wnK6db+SYtrx98GoJn+4/TCVnQm56qXWAkrK1YjKh+h43JI8ZEtnFHXl2/Kz+7sfxmfOblraawdOjuho+JCFnu8kBn0dGTv84bYqsScuoDqGYAj/VWktaZryvb1CHJjSLym0pRZmXDz/J+qQYNx2YuY/dxzQjK4WZIBOgW+EnldGYOWNzFekTC4fjfJK6y6PK6gEfwBhONn2ccNaSCgi1ho=
    on:
      tags: true
      repo: higlass/higlass-labelled-points-track
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: hCKQH/ickwzXBpnl/jyVd/8yc14N8rsmdMMlHOHH4Nspt2PhqhxYSVvMt9rLF4anHmp5HfgxWYxPsigDdhZqfY6j/k1LixpVP5LNp5nd3ESv88kW0m4uwVTU7Z8Ig3ucS65cFcONoDYPERGCPZVuJYGGwDiF6BnYOcWN/ah7WD6W7o/52TjevEemI6PfhzroEOUVYHOhxvfSShpWdzl4RkFVnV5SoAOPVaIRTCaXMcuivTYRv3/301lH7dtjRhGlo3lVhKX4M+vZBqQB0Nc8+mp239lLo03ybVUjDf5RCiNaEuOFuIWOjFQ9K+4w/62wy8eH+CRrCzlPHBw3WA5mtztB0uVBTD5yD8QWgrf9jdesREtpFk6dgldhbU4csCikN7qPTmwxW1q3F2/h3xUZd4O+ybmyXFek0iXTAWM3ACAfweTwyG/JFal/n0DduorzGcE2zEMwLzvyuG3H+F7+IwYppjfKFM4fKpbrr4SA7EyDtMn5EiFK46cqhH/Q0nA7bZPbtQ6jEx9ypjjYIhtqjwg8vqsBWe71c0I3hUL8Cd1pijXipW8HigVM29KzdYGXPBVt0dRP/rcsCx8Qm2yWczscuX7ekHa4GoLCt2cGBJv6OI0vv4nTrBxmYWydMrDUjte0whs3o6gCd5GK9rN+bwhqgx5W8Kd4ffCIkkJ3dwo=
    file: dist.zip
    on:
      repo: higlass/higlass-labelled-points-track
